[cargo-new]
name = "Jan Pikl"
email = "pikl.jan@gmail.com"
vcs = "git"

[alias]
i = "install"
l = "install --list"
up = "install-update --all"
un = "uninstall"
b = "build"
c = "check"
t = "test"
r = "run"
