#!/usr/bin/env sh

# Execute command with dotfiles environment
alias dotenv='env GIT_DIR=$HOME/.dotfiles.git GIT_WORK_TREE=$HOME'

# Git for dotfiles
alias dotfiles='dotenv git'

# VS Code for dotfiles
alias dotcode='dotenv code'

# Grep with colors
alias grep='grep --color=auto'

# List files with colors by default
alias ls='ls --color=auto'

# List files, include hiden
alias la='ls -a'

# List files in human-readable long format
alias ll='ls -lh'

# List files in human-readable long format, include hidden
alias lla='ls -lha'

# Create nested directories by default
alias mkdir='mkdir -p'

## Remove files with recursion and force
alias rmrf='rm -rf'

## Sort lines, output unique results
alias sortu='sort -u'

## Sort lines, output unique results with their count
sortuc() {
  sort | uniq -c | sort -nr
}

# Count input lines
alias wcl='wc -l'

# Prefer nvim over vim/vi
if [ -x "$(command -v nvim)" ]; then
    alias vim=nvim
    alias vi=nvim
fi

# Helix editor shortcut
alias hx=helix
