#!/usr/bin/env bash

# Shell options
shopt -s histappend # Append entries to history file instead of overwriting it
shopt -s globstar   # Enable recursive `**` glob pattern
shopt -s failglob   # Treat glob patterns with no matches as errors
shopt -s direxpand  # Expand directory variables (like $HOME) for auto completion

# History configuration
export HISTFILE=~/.bash_history          # Save file
export HISTSIZE=1000                     # Max records in memory
export HISTFILESIZE=1000                 # Max records saved to file
export HISTCONTROL=ignorespace:erasedups # Ignore commands starting with space + erase duplicates

# Initialize starship prompt or use fallback
if [[ -x "$(command -v starship)" ]]; then
    eval "$(starship init bash)"
else
     # ''
     # '<cyan>$WORKDIR</cyan>'
     # 'at <yellow>$TIME</yellow> err <red>$LAST_EXIT_CODE</red> ❭ '
     PS1="\n\[\e[36m\]\w\[\e[0m\]\nat \[\e[33m\]\t\[\e[0m\] err \[\e[31m\]\$?\[\e[0m\] ❭ "
fi

# Arch Linux "command not found" support provided by `pgkfile` package
if [[ -f /usr/share/doc/pkgfile/command-not-found.bash ]]; then
  source /usr/share/doc/pkgfile/command-not-found.bash
fi

# Better shell history (Ctrkl+R) with atuin
if [[ -x "$(command -v atuin)" ]]; then
  [[ -f ~/.config/bash/preexec ]] && source ~/.config/bash/preexec
  eval "$(atuin init bash --disable-up-arrow)"
fi
