[time]
disabled = false

[shlvl]
disabled = false

[status]
disabled = false
map_symbol = true
symbol = "🔥"
sigint_symbol = "💀"
format = "[$symbol $status]($style) " # We added an extra space after the symbol
